use_gpu: True

data:
    set_name: autoenc
    max_workers: 4
    valid_split: 0.2

model:
    class: transformer

train:
    num_epochs: 24
    optim:
        learn_rate: 0.1
        weight_decay: 0.0
    batch_size: 2
    print_iter: 2
    save_model: True

valid:
    batch_size: 2

remarks: Run on small set to see if model overfits.
